#ifndef CLIENT_SYNTHETIC_HOOK_HOOKS_MINECRAFTUIRENDERCONTEXT_MINECRAFTUIRENDERCONTEXT
#define CLIENT_SYNTHETIC_HOOK_HOOKS_MINECRAFTUIRENDERCONTEXT_MINECRAFTUIRENDERCONTEXT

#include "../../Hook.h"

class Hook_MinecraftUIRenderContext : public Hook {
public:
    Hook_MinecraftUIRenderContext(Manager*);
    void init() override;
};

#endif /* CLIENT_SYNTHETIC_HOOK_HOOKS_MINECRAFTUIRENDERCONTEXT_MINECRAFTUIRENDERCONTEXT */